---
# tasks file for ansible-role

- include: sudo.yml
  when: nrpe_disable_sudo_requiretty

- include: opsview.yml
  when: ansible_os_family == "RedHat" and install_opsview and not install_nrpe

- include: nrpe.yml
  when: ansible_os_family == "Debian" and not install_opsview and install_nrpe
