---

- hosts: all
  gather_facts: true
  become: true
  vars_files:
    - /defaults/main.yml
  tasks:

#      name: bind-utils
    - include: opsview.yml
      when: ansible_os_family == "RedHat"

#      name: proxmox-ve postfix open-iscsi
    - include: nrpe.yml
      when: ansible_os_family == "Debian"
