---
# tasks file for ansible-role-nrpe
 
- name: Include vars of stuff.yaml into the 'defaults' variable (2.2).
  include_vars:
    file: ../defaults/main.yml
    name: main

- name: Install nrpe package
  apt: state=present name=nagios-nrpe-server
  notify:
    - "restart nagios-nrpe-server"

- name: Remove all hardcoded command settings from default nrpe.cfg
  lineinfile:
    state: absent
    regexp: '^command\['
    path: '/etc/nagios/nrpe.cfg'
  notify:
    - "restart nrpe"
  when: remove_hardcoded_checks|default(false)|bool
  
- name: copy custom plugin files
  copy: src=../templates/{{ item }} dest={{ nagios_plugins_dir }} mode=0755

  with_items:
    - check_diskstat.sh
    - check_raid.pl

- name: Template in override config file 
  template: src=../templates/override.cfg.j2 dest={{ nagios_cfg_file }} mode=0644
            owner={{ nrpe_user }} group={{ nrpe_group }}
  notify:
    - "restart nagios-nrpe-server"

- name: Template in custom checks config file
  template: src="../templates/check_nagios.cfg.j2"
            dest={{ nagios_include_dir }}/{{ nagios_custom_checks_file }}
            mode=0640
            owner={{ nrpe_user }} group={{ nrpe_group }}
  #tags: update_nrpe_cfg
  notify:
    - "restart nagios-nrpe-server"

- name: Make sure nrpe is started and enabled
  service: name=nagios-nrpe-server state=started enabled=yes

- name: Allow nrpe_user to run some HP commands on HP systems
  template: src=sudoers_nrpe_hp dest=/etc/sudoers.d/sudoers_nrpe_hp mode=640
  when: ansible_system_vendor == "HP"
